Document: mingw-w64-wxmsw
Title: Debian mingw-w64-wxmsw Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-wxmsw is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-wxmsw/mingw-w64-wxmsw.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-wxmsw/mingw-w64-wxmsw.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-wxmsw/mingw-w64-wxmsw.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-wxmsw/html/index.html
Files: /usr/share/doc/mingw-w64-wxmsw/html/*.html
